CONNECT TO BANCO6;

-- Projeto 6 COBOL + DB2
-- Preparacao manual do banco: cria tabelas e cadastra clientes e transacoes iniciais.
-- Nesta versao, o COBOL NAO carrega CLIENTES.TXT.
-- O COBOL apenas consulta a tabela CLIENTES, processa TRANSACOES.TXT,
-- atualiza saldos e grava TRANSACOES, ERROS_PROCESSAMENTO e HISTORICO_TRANSACOES.

CREATE TABLE CLIENTES (
    CLI_ID          INTEGER      NOT NULL,
    CLI_NOME        VARCHAR(30)  NOT NULL,
    CLI_SALDO       DECIMAL(9,0) NOT NULL,
    DT_ATUALIZACAO  DATE,
    PRIMARY KEY (CLI_ID)
);

CREATE TABLE TRANSACOES (
    TRX_ID            INTEGER      NOT NULL,
    CLI_ID            INTEGER      NOT NULL,
    TRX_TIPO          CHAR(1)      NOT NULL,
    TRX_VALOR         DECIMAL(9,0) NOT NULL,
    DT_PROCESSAMENTO  DATE,
    PRIMARY KEY (TRX_ID)
);

CREATE TABLE ERROS_PROCESSAMENTO (
    ID_ERRO         INTEGER GENERATED ALWAYS AS IDENTITY,
    CLI_ID          INTEGER,
    DESCRICAO_ERRO  VARCHAR(100),
    DT_OCORRENCIA   TIMESTAMP
);

CREATE TABLE HISTORICO_TRANSACOES (
    HIST_ID              INTEGER GENERATED ALWAYS AS IDENTITY,
    TRX_ID               INTEGER,
    CLI_ID               INTEGER,
    TRX_TIPO             CHAR(1),
    TRX_VALOR            DECIMAL(9,0),
    SALDO_ANTERIOR       DECIMAL(9,0),
    SALDO_NOVO           DECIMAL(9,0),
    STATUS_PROCESSAMENTO VARCHAR(30),
    DESCRICAO            VARCHAR(100),
    DT_HISTORICO         TIMESTAMP
);

CREATE INDEX IDX_TRANSACOES_CLI_ID ON TRANSACOES (CLI_ID);
CREATE INDEX IDX_ERROS_CLI_ID ON ERROS_PROCESSAMENTO (CLI_ID);

-- Clientes cadastrados manualmente no DB2.
-- O cliente 00456 ja entra com o nome/saldo atualizado, simulando que a base oficial ja esta pronta.
INSERT INTO CLIENTES (CLI_ID, CLI_NOME, CLI_SALDO, DT_ATUALIZACAO)
VALUES (123, 'JOAO SILVA', 10000, CURRENT DATE);

INSERT INTO CLIENTES (CLI_ID, CLI_NOME, CLI_SALDO, DT_ATUALIZACAO)
VALUES (456, 'MARIA SOUZA ATUALIZADA', 26000, CURRENT DATE);

INSERT INTO CLIENTES (CLI_ID, CLI_NOME, CLI_SALDO, DT_ATUALIZACAO)
VALUES (789, 'CARLOS PEREIRA', 5000, CURRENT DATE);

INSERT INTO CLIENTES (CLI_ID, CLI_NOME, CLI_SALDO, DT_ATUALIZACAO)
VALUES (999, 'CLIENTE SEM NOME', 900, CURRENT DATE);


-- Transacoes cadastradas manualmente no DB2.
-- O COBOL continua lendo TRANSACOES.TXT para validar e processar as regras,
-- mas a tabela TRANSACOES ja fica previamente populada para demonstrar
-- que os dados tambem podem vir do banco.
INSERT INTO TRANSACOES (TRX_ID, CLI_ID, TRX_TIPO, TRX_VALOR, DT_PROCESSAMENTO)
VALUES (10, 123, 'C', 500, CURRENT DATE);

INSERT INTO TRANSACOES (TRX_ID, CLI_ID, TRX_TIPO, TRX_VALOR, DT_PROCESSAMENTO)
VALUES (20, 123, 'D', 200, CURRENT DATE);

INSERT INTO TRANSACOES (TRX_ID, CLI_ID, TRX_TIPO, TRX_VALOR, DT_PROCESSAMENTO)
VALUES (30, 456, 'D', 1000, CURRENT DATE);

INSERT INTO TRANSACOES (TRX_ID, CLI_ID, TRX_TIPO, TRX_VALOR, DT_PROCESSAMENTO)
VALUES (40, 789, 'D', 6000, CURRENT DATE);

INSERT INTO TRANSACOES (TRX_ID, CLI_ID, TRX_TIPO, TRX_VALOR, DT_PROCESSAMENTO)
VALUES (50, 11111, 'C', 100, CURRENT DATE);

INSERT INTO TRANSACOES (TRX_ID, CLI_ID, TRX_TIPO, TRX_VALOR, DT_PROCESSAMENTO)
VALUES (60, 123, 'X', 100, CURRENT DATE);

INSERT INTO TRANSACOES (TRX_ID, CLI_ID, TRX_TIPO, TRX_VALOR, DT_PROCESSAMENTO)
VALUES (70, 123, 'C', 0, CURRENT DATE);

INSERT INTO TRANSACOES (TRX_ID, CLI_ID, TRX_TIPO, TRX_VALOR, DT_PROCESSAMENTO)
VALUES (80, 999, 'D', 100, CURRENT DATE);

INSERT INTO TRANSACOES (TRX_ID, CLI_ID, TRX_TIPO, TRX_VALOR, DT_PROCESSAMENTO)
VALUES (90, 456, 'C', 250, CURRENT DATE);

COMMIT;

CONNECT RESET;
