CONNECT TO BANCO6;

SELECT * FROM CLIENTES ORDER BY CLI_ID;
SELECT * FROM TRANSACOES ORDER BY TRX_ID;
SELECT * FROM ERROS_PROCESSAMENTO ORDER BY ID_ERRO;
SELECT * FROM HISTORICO_TRANSACOES ORDER BY HIST_ID;

CONNECT RESET;
